[general]
port = 80
root = "/home/sws/public"
cache-control-headers = false

[advanced]

[[advanced.headers]]
source = "**"
[advanced.headers.headers]
Cache-Control = "no-cache"
Content-Security-Policy = "frame-ancestors 'self'"
X-Frame-Options = "SAMEORIGIN"
